# Generated by Django 3.0.3 on 2020-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nome',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
    ]
