# Generated by Django 3.0.3 on 2020-02-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nome',
            new_name='titulo',
        ),
    ]
