# Generated by Django 3.0.3 on 2020-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200205_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=1, upload_to='post/'),
            preserve_default=False,
        ),
    ]
